
name: workflow on multiple repos
on: [push, pull_request]
env:
  MY_NAME: VU Khac Tri

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
    - name: checkout a
      uses: actions/checkout@v2
      with: 
        repository: mu-triv/github_actions_a
        path: github_actions_a
    - name: print README a
      run: |
        ls -la .
        cat README.md
        echo "user ID is: ${UID}"
        echo "${{ env.MY_NAME }}"
        echo "${MY_NAME}"
      working-directory: ./github_actions_a

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        retention-days: 1
        path: |
          ./github_actions_a/README.md
          ./github_actions_a/for_archive/test1.md

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
    - name: checkout b
      uses: actions/checkout@v2
      with: 
        repository: mu-triv/github_actions_b
        path: github_actions_b

    - name: print README b
      run: |
        ls -la .
        cat README.md
      working-directory: ./github_actions_b

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact

    - name: print README a
      run: |
        ls -la .
        ls -la ./for_archive/.
        cat README.md
