
name: workflow on multiple repos
on: [push, pull_request]

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
    - name: checkout a
      uses: actions/checkout@v2
      with: 
        repository: mu-triv/github_actions_a
        path: github_actions_a
    - name: run a
      run: |
        ls -la .
        cat README.md
      working-directory: ./github_actions_a
      
  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
    - name: checkout b
      uses: actions/checkout@v2
      with: 
        repository: mu-triv/github_actions_b
        path: github_actions_b

    - name: run b
      run: |
        ls -la .
        cat README.md
      working-directory: ./github_actions_b

