
name: workflow on multiple repos
on: [push, pull_request]

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
    - name: run a
      uses: actions/checkout@v2
      run: ls -la .
      with: mu-triv/github_actions_a
      working-directory: ./github_actions_a
      
  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
    - name: run b
      uses: actions/checkout@v2
      run: ls -la .
      with: mu-triv/github_actions_b
      working-directory: ./github_actions_b


